//
// Created by luo on 2021/10/7.
//

#ifndef PM_TINY_PM_TINY_H
#define PM_TINY_PM_TINY_H

#define PM_TINY_PROG_STATE_NO_RUN 0
#define PM_TINY_PROG_STATE_RUNING 1
#define PM_TINY_PROG_STATE_STARTUP_FAIL 2
#define PM_TINY_PROG_STATE_REQUEST_STOP 3
#define PM_TINY_PROG_STATE_STOPED 4
#define PM_TINY_PROG_STATE_EXIT 5

#define PM_TINY_FRAME_TYPE_SHOW_LOG 0x30

#endif //PM_TINY_PM_TINY_H
